---
title: "team2_work"
author: "Liam D. Bailey & Lena Lickteig"
date: "12/02/2021"
output: html_document
---

```{r, include = FALSE}

#Load packages
library(sf)
library(osmdata)
library(raster)
library(dplyr)
library(ggplot2)
library(here)
library(leaflet)

#Options
options(scipen = 200)

```

Load the data

```{r}

df <- read.csv2(here::here("./data/social-housing-paris/logements-sociaux-finances-a-paris.csv"),
                stringsAsFactors = FALSE) %>% 
  janitor::clean_names()

df_sf <- sf::read_sf(here::here("./data/social-housing-paris/logements-sociaux-finances-a-paris.geojson"))

```

Districts

```{r}

paris <- raster::getData(name = "GADM", country = "FRA", level = 3) %>% 
  sf::st_as_sf() %>% 
  filter(NAME_1 == "Île-de-France" & NAME_2 == "Paris")

```

##ggplot

```{r}

ggplot()+
  geom_sf(data = paris) +
  geom_sf(data = df_sf)

```

Contour map

```{r}

housing_coords <- df_sf %>% 
  sf::st_coordinates() %>% 
  as_tibble()

ggplot() +
  stat_density2d_filled(data = housing_coords, aes(x = X, y = Y),
                        contour_var = "ndensity") +
  geom_sf(data = paris, fill = NA, colour = "black", size = 1, alpha = 0.75) +
  scale_fill_viridis_d(name = "Relative housing density",
                      labels = c("0-0.1", "0.1-0.2", "0.2-0.3", "0.3-0.4",
                                 "0.4-0.5", "0.5-0.6", "0.6-0.7", "0.7-0.8",
                                 "0.8-0.9", "0.9-1.0")) +
  theme(panel.background = element_rect(fill = "#440154FF"),
        panel.grid = element_blank())

```

##Leaflet

Create a leaflet map of the social housing

Per district, determine the housing/km2

```{r}

houses_per_district <- df_sf %>% 
  sf::st_within(paris, sparse = FALSE) %>% 
  which(arr.ind = TRUE) %>% 
  as_tibble() %>% 
  group_by(col) %>% 
  summarise(nr_houses = n())

```

```{r}

paris_density <- paris %>% 
  mutate(area = as.numeric(sf::st_area(.))/1000000,
         nr_houses = houses_per_district$nr_houses,
         density = nr_houses/area)

```

```{r}

bins <- c(0, 10, 20, 30, 40, 50, 60, 70, Inf)
pal <- colorBin("YlOrRd", domain = paris_density$density, bins = bins)

leaflet(paris_density) %>%
  addTiles(group = "OSM") %>%
  addPolygons(
  fillColor = ~pal(density),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  popup = ~NAME_3)

```

Add HTML labels

```{r}

labels <- sprintf(
  "<strong>%s</strong><br/>%g social housing / km<sup>2</sup>",
  paris_density$NAME_3, round(paris_density$density, 2)
) %>% lapply(htmltools::HTML)

leaflet(paris_density) %>%
  addTiles(group = "OSM") %>%
  addPolygons(
    fillColor = ~pal(density),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"))

```

Create a loop to extract information for every year

```{r}

paris <- paris %>% 
  mutate(polygon_nr = 1:n())

housing_peryear <- purrr::map_df(.x = unique(df_sf$annee),
           .f = function(year, paris_districts){
             
             print(year)
             
             houses_per_year <- df_sf %>% 
               filter(annee == year)
             
             houses_per_district <- houses_per_year %>% 
               sf::st_within(paris_districts, sparse = FALSE) %>% 
               which(arr.ind = TRUE) %>% 
               as_tibble() %>% 
               group_by(col) %>% 
               summarise(nr_houses = n()) %>% 
               rename(polygon_nr = col)
             
             paris_density <- paris_districts %>% 
               left_join(houses_per_district, by = "polygon_nr") %>% 
               mutate(area = as.numeric(sf::st_area(.))/1000000,
                      density = nr_houses/area,
                      start = as.Date(paste0(year, "/01/01")),
                      end = as.Date(paste0(year, "/12/31")))
             
             paris_density
             
           }, paris_districts = paris)

```

Add a timeline

```{r}

library(leaftime)

points_over_time <- df_sf %>% 
  mutate(start = as.Date(paste0(annee, "/01/01")),
         end = as.Date(paste0(annee, "/12/31"))) %>% 
  mutate(coord = sf::st_coordinates(.))

leaflet() %>%
  addTiles(group = "OSM") %>% 
  addTimeline(data = points_over_time)

```

